# Generated by Django 4.1.4 on 2023-01-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.IntegerField()),
                ('rental_value', models.FloatField()),
                ('garage_value', models.FloatField()),
                ('expenses_value', models.FloatField()),
                ('total_value', models.FloatField()),
            ],
        ),
    ]
