# Generated by Django 4.1.4 on 2023-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_door_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_picture',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
