# Generated by Django 4.1.4 on 2023-02-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_apartment_picture_apartment_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='total_value',
        ),
    ]
