# Generated by Django 4.1.4 on 2023-02-06 23:25

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_remove_apartment_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='total_value',
            field=computed_property.fields.ComputedFloatField(compute_from='calculate_total_value', default=1, editable=False),
            preserve_default=False,
        ),
    ]
