# Generated by Django 4.1.4 on 2023-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_images'),
        ),
    ]
