# Generated by Django 4.1.4 on 2023-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_delete_apartment_delete_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='receipt_of_payent',
            new_name='receipt_of_payment',
        ),
        migrations.AddField(
            model_name='rent',
            name='has_debt',
            field=models.BooleanField(default=False),
        ),
    ]
