# Generated by Django 4.1.4 on 2023-02-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_total_value'),
        ('tenants', '0002_tenant_is_active_tenant_tenant_picture'),
        ('rentals', '0003_rename_receipt_of_payent_rent_receipt_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='apartment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='apartments.apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
