# Generated by Django 4.1.4 on 2023-02-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_is_active_tenant_tenant_picture'),
        ('apartments', '0005_apartment_total_value'),
        ('rentals', '0004_rent_apartment_rent_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='tenants.tenant'),
        ),
    ]
